// import Head from 'next/head'
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'

// export default function Home() {
//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <main className={styles.main}>
//         <h1 className={styles.title}>
//           Welcome to <a href="https://nextjs.org">Next.js!</a>
//         </h1>

//         <p className={styles.description}>
//           Get started by editing{' '}
//           <code className={styles.code}>pages/index.js</code>
//         </p>

//         <div className={styles.grid}>
//           <a href="https://nextjs.org/docs" className={styles.card}>
//             <h2>Documentation &rarr;</h2>
//             <p>Find in-depth information about Next.js features and API.</p>
//           </a>

//           <a href="https://nextjs.org/learn" className={styles.card}>
//             <h2>Learn &rarr;</h2>
//             <p>Learn about Next.js in an interactive course with quizzes!</p>
//           </a>

//           <a
//             href="https://github.com/vercel/next.js/tree/canary/examples"
//             className={styles.card}
//           >
//             <h2>Examples &rarr;</h2>
//             <p>Discover and deploy boilerplate example Next.js projects.</p>
//           </a>

//           <a
//             href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//           >
//             <h2>Deploy &rarr;</h2>
//             <p>
//               Instantly deploy your Next.js site to a public URL with Vercel.
//             </p>
//           </a>
//         </div>
//       </main>

//       <footer className={styles.footer}>
//         <a
//           href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//           target="_blank"
//           rel="noopener noreferrer"
//         >
//           Powered by{' '}
//           <span className={styles.logo}>
//             <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
//           </span>
//         </a>
//       </footer>
//     </div>
//   )
// }

import Navbar from "../components/Navbar";
import styles from "../styles/index.module.css";

export default function index(){
  return(
    <div>
      <header>
        <Navbar />
      </header>
      <div className="typography">
          <div className="c_container">
              <div className="c_row mb_5">
                  <h1 className="textcenter m_auto w_100 display_text1">Hello
                      <span className="display_text2 Primary_1">Jumbaya</span>
                  </h1>
              </div>
              <div className="c_row">
                  <h1 className="textcenter m_auto w_100">Jumbaya</h1>
                  <h2 className="textcenter m_auto Primary_1 w_100">Verification</h2>
                  <h3 className="textcenter m_auto Primary_1 w_100">Verification 1</h3>
                  <h4 className="textcenter m_auto Primary_1 w_100">Verification 2</h4>
                  <p className="textcenter body1 mb_5">Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repellat sunt mollitia, doloremque consectetur officia molestiae aut quas doloribus hic sapiente sit rerum consequatur quis laboriosam quibusdam ad repudiandae voluptate autem.</p>
                  <p className="textcenter m_auto body2 w_100 mb_5">Lorem ipsum dolor</p>
                  <button className={ `${styles.submitbtn} ${styles.m_auto} `} type="button">Lorem</button>
                  <p className="textcenter small w_100">Lorem ipsum dolor</p>
                  <p className="textcenter indi_msgs w_100">Lorem ipsum dolor</p>
              </div>
          </div>
      </div>
    </div>
  )
}
